import Foundation

/// The identity of a note.
///
/// Identifiers are generated by the client, never by the database. Two offline
/// devices can create notes without colliding, which is the first of the V2
/// seams — the server accepts an identity rather than assigning one.
public struct NoteID: Hashable, Sendable, Codable {
    public let value: UUID

    public init(_ value: UUID = UUID()) {
        self.value = value
    }
}

extension NoteID: CustomStringConvertible {
    public var description: String { value.uuidString }
}
